### ISSUE TITLE
request

### ISSUE THREAD

**Issue by RaquisDawLn** [PandeoF1/px_botnet#6]
Can you add windows functionality or just straight up port to windows?

**Comment by PandeoF1** [comment]
Actually we use <sys/socket.h> for all the methods. But the core of the communication for the http request was made with sys/socket and with <winsock2.h>. So actually we can't make a windows version because the attack methods wasn't compatible with windows. The first real problem with windows is windows defender.

**Comment by RaquisDawLn** [comment]
> Actually we use <sys/socket.h> for all the methods. But the core of the communication for the http request was made with sys/socket and with <winsock2.h>. So actually we can't make a windows version because the attack methods wasn't compatible with windows. The first real problem with windows is windows defender.

You could re-write them to support windows or make a port to windows also for windows defender you would just have to encrypt your payload

**Comment by PandeoF1** [comment]
I haven't really the time to make a windows version actually. But maybe in the futur
